version: "3"

services:

  sonarqube:
    build:
      context: ../dockerfiles/sonarqube

    image: sonarqube-scanner:lts

    hostname: ${SONARQUBE_CONTAINER_HOSTNAME}

    container_name: ${SONARQUBE_CONTAINER_NAME}

    restart: "always"

    ports:
      - "9012:9000"

    networks:
      - internal_network
      - external_network

    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db_sonar:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

    volumes:
      - ../var/sonarqube/conf:/opt/sonarqube/conf:z
      - ../var/sonarqube/data:/opt/sonarqube/data:z
      - ../var/sonarqube/extensions:/opt/sonarqube/extensions:z
      - ../var/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins:z
      - ${PATH_PROJECT_VOLUME}:/website_test:z

    depends_on:
      - db_sonar

  db_sonar:
    image: postgres:latest

    container_name: ${SONARQUBE_DB_CONTAINER_NAME}

    hostname: ${SONARQUBE_DB_CONTAINER_HOSTNAME}

    restart: "always"

    networks:
      - internal_network
    
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    
    volumes:
      - ../var/sonarqube/database:/var/lib/postgresql:z
      - ../var/sonarqube/database/data:/var/lib/postgresql/data:z

networks:
  internal_network:
    name: net_lampp
  external_network:
    external: true